# Generated by Django 5.0.3 on 2024-03-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comic",
            name="rating",
            field=models.FloatField(default=0),
        ),
    ]
